In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('gemstone.csv')
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [4]:
df=df.drop(labels=['id'],axis=1)
df.head()

   carat        cut color clarity  depth  table     x     y     z  price
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [5]:
x=df.drop(["price"],axis=1)
y=df[['price']]

In [6]:
categorical_colm=x.select_dtypes(include='object').columns
numerical_colm=x.select_dtypes(exclude='object').columns

In [7]:
cut_categories=["Fair","Good","Very Good","Premium","Ideal"]
colour_categories=["D" ,"E" ,"F" , "G" ,"H", "I", "J"]
clarity_categories=["I1","SI2" ,"SI1" ,"VS2" , "VS1" , "VVS2" , "VVS1" ,"IF"]

In [8]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [9]:
num_pipeline=Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy='median')),
        ('scaler',StandardScaler())]
)
cate_pipeline=Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy='most_frequent')),
        ('ordinalencoder',OrdinalEncoder(categories=[cut_categories,colour_categories,clarity_categories])),
        ('scaler',StandardScaler())]
)

preprocessor=ColumnTransformer([
   ('num_pipeline',num_pipeline,numerical_colm),
   ('cat_pipeline',cate_pipeline,categorical_colm)
])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test=train_test_split(x,y,test_size=0.30,random_state=30)

In [12]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [13]:
X_train.head()

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.975439,-0.849607,-0.121531,-1.042757,-1.080970,-1.123150,0.874076,1.528722,1.352731
1,0.235195,1.833637,-0.121531,0.318447,0.279859,0.485354,-2.144558,-0.935071,-0.646786
2,0.494617,0.815855,0.399800,0.570855,0.606458,0.673737,-0.132136,0.296826,0.686225
3,-1.018676,0.260701,0.921131,-1.214034,-1.244270,-1.195605,-0.132136,0.296826,0.019720
4,-0.953821,-0.664555,-0.642862,-1.069801,-1.044681,-1.094168,0.874076,2.144670,1.352731

In [14]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression

In [15]:
from sklearn.metrics import r2_score

In [16]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [23]:
def evaluate_model(true,predicted):
    mse=mean_squared_error(true,predicted)
    mae=mean_absolute_error(true,predicted)
    r_score=r2_score(true,predicted)
    return mse,mae,r_score

In [26]:
models={'LinearRegression':LinearRegression(),
        'RandomForestRegressor':RandomForestRegressor(),
        'DecisionTreeRegressor':DecisionTreeRegressor()
        }
trained_model_list=[]
model_list=[]
r2_score=[]
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    
    y_pred=model.predict(X_test)
    mse,mae,r_score=evaluate_model(y_test,y_pred)
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    print("model training performance")
    print("mse",mse)
    print('mae',mae)
    print('r2_score',r_score)
    #print('=',*35)
    print('\n')

TypeError: 'list' object is not callable